/*

Brings up a Save JFileChooser to export the Unavailabilities report as a .txt file

By Daniel Vella

*/

package gui;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import managers.DoctorIO;

public class ExportReportPanel extends javax.swing.JPanel 
   {

   private int userOption_;
   private File reportToExport_;
   private File workingDirectory_;
   
   public ExportReportPanel() 
      {
         
      initComponents();
      
      saveDialog_.setDialogTitle("Export Report");
      saveDialog_.setFileFilter(new FileTypeFilter(".txt", "Text File"));
      
      // Opens window in current directory 
      workingDirectory_ = new File(System.getProperty("user.dir"));
      saveDialog_.setCurrentDirectory(workingDirectory_);
       
      // Shows save dialog
      userOption_ = saveDialog_.showSaveDialog(null);

      if (userOption_ == JFileChooser.APPROVE_OPTION) 
         {
         
         reportToExport_ = saveDialog_.getSelectedFile();
         
         try
            {
               
            FileWriter fw = new FileWriter(reportToExport_ + ".txt");
            fw.write(DoctorIO.getFullReport());
            fw.flush();
            fw.close();     
            JOptionPane.showMessageDialog(null, "Report Exported Succesfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            }
         catch (IOException e2)
            {
               
            JOptionPane.showMessageDialog(null, e2.toString());
            
            }
         
         }
   
      }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      saveDialog_ = new javax.swing.JFileChooser();

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(saveDialog_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(saveDialog_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JFileChooser saveDialog_;
   // End of variables declaration//GEN-END:variables
}
