/*

Brings up a JFileChooser to locate and import the Doctor Availabilities .txt file

By Daniel Vella

*/

package gui;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import managers.DoctorIO;

public class ImportAvailability extends javax.swing.JPanel 
   {
   
   private int reply_;
   private String message_;
   private File schedule_;
   private File workingDirectory_;
   private Integer i_ = 1;

   public ImportAvailability() 
      {
                       
      initComponents();
      
      // Starting file choice functions
      chooser_.setDialogTitle("Import Availabilities");
      chooser_.setFileFilter(new FileTypeFilter(".txt", "Text File"));
      
      // Opens window in current directory 
      workingDirectory_ = new File(System.getProperty("user.dir"));
      chooser_.setCurrentDirectory(workingDirectory_);
      
      chooser_.showOpenDialog(null);
      
      schedule_ = chooser_.getSelectedFile();

      try
         {
            
         message_ = "Are you sure you want to import file " + schedule_.getName() + " ?";
         
         reply_ = JOptionPane.showConfirmDialog(null, message_, "Confirm", JOptionPane.YES_NO_OPTION);
      
         // JOptionPane options handling 
         while (reply_ != JOptionPane.YES_OPTION && i_ != 3)
            {
            
            chooser_.showOpenDialog(null);
            reply_ = JOptionPane.showConfirmDialog(null, message_, message_, JOptionPane.YES_NO_OPTION);
            i_++;

            }
      
         if (i_ == 3)
            {
        
            JOptionPane.showMessageDialog(null, "You cancelled 3 times in a row, try again later", "Error", JOptionPane.WARNING_MESSAGE);

            }
         
         } 
      
      catch (NullPointerException e)
         
         {
         
         System.out.println(e.toString());
         
         }
      
      try 
         {

         DoctorIO.availabilityUpdate(schedule_);
         JOptionPane.showMessageDialog(null, "Import successful", "Complete", JOptionPane.INFORMATION_MESSAGE);
            
         }
      catch (ArrayIndexOutOfBoundsException e)
         {
            
         JOptionPane.showMessageDialog(null, "Availabilities not imported. Make sure it's the correct file", "Error", JOptionPane.WARNING_MESSAGE);
         
         }
      catch (FileNotFoundException e)
         {
            
         JOptionPane.showMessageDialog(null, "File not found. Make sure it's the correct file", "Error", JOptionPane.WARNING_MESSAGE);

         }
      catch (NullPointerException e)
         {
            
         JOptionPane.showMessageDialog(null, "Availabilities not imported. Make sure it's the correct file", "Error", JOptionPane.WARNING_MESSAGE);

         }
      catch (Exception e)
         {
         
         JOptionPane.showMessageDialog(null, "Availabilities not imported. Make sure it's the correct file", "Error", JOptionPane.WARNING_MESSAGE);
         
         }
      }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      chooser_ = new javax.swing.JFileChooser();

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(chooser_, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(chooser_, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JFileChooser chooser_;
   // End of variables declaration//GEN-END:variables
}
