/*

Part of the ViewAvailableDoctorPanel, which uses GridLayout to set 3 columns
This panel is added in the left column to show Medical Disciplines

By Daniel Vella

*/

package gui;

import defaultpackage.Doctor;
import managers.DoctorManager;

public class LeftDisciplinesListPanel extends javax.swing.JPanel 
   {
   
   private Doctor[] doctors_;
   private MiddleAvailabilityPanel showAvailPanel_;
   
   public LeftDisciplinesListPanel(MiddleAvailabilityPanel showAvail) 
   
      {
         
      initComponents();
      this.showAvailPanel_ = showAvail;
      showAvailPanel_.setVisible(false);
      
      }
   
   // Method to get availabilities and show panel 
   private void showAvailabilities()
      {
         
      showAvailPanel_.setDoctorsArray(doctors_);
      showAvailPanel_.setVisible(true);

      }

      
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      backgroundDLP_ = new javax.swing.JPanel();
      disciplinesTitleLabel_ = new javax.swing.JLabel();
      cardiologyButton_ = new javax.swing.JButton();
      pulmonologyButton_ = new javax.swing.JButton();
      infectiousButton_ = new javax.swing.JButton();
      haematologyButton_ = new javax.swing.JButton();
      intensiveCareButton_ = new javax.swing.JButton();
      neurologyButton_ = new javax.swing.JButton();
      ophtalmologyButton_ = new javax.swing.JButton();
      orthopaedicsButton_ = new javax.swing.JButton();
      urologyButton_ = new javax.swing.JButton();
      surgeryButton_ = new javax.swing.JButton();
      guideLabel_ = new javax.swing.JLabel();

      setBackground(new java.awt.Color(255, 255, 255));
      setMinimumSize(new java.awt.Dimension(191, 200));
      setPreferredSize(new java.awt.Dimension(191, 200));

      backgroundDLP_.setBackground(new java.awt.Color(255, 255, 255));
      backgroundDLP_.setLayout(new java.awt.GridBagLayout());

      disciplinesTitleLabel_.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
      disciplinesTitleLabel_.setText("Disciplines");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
      backgroundDLP_.add(disciplinesTitleLabel_, gridBagConstraints);

      cardiologyButton_.setText("Cardiology");
      cardiologyButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            cardiologyButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(cardiologyButton_, gridBagConstraints);

      pulmonologyButton_.setText("Pulmonology");
      pulmonologyButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            pulmonologyButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(pulmonologyButton_, gridBagConstraints);

      infectiousButton_.setText("Infectious Disease");
      infectiousButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            infectiousButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 4;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(infectiousButton_, gridBagConstraints);

      haematologyButton_.setText("Hematology");
      haematologyButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            haematologyButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 5;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(haematologyButton_, gridBagConstraints);

      intensiveCareButton_.setText("Intensive Care Medicine");
      intensiveCareButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            intensiveCareButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 6;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(intensiveCareButton_, gridBagConstraints);

      neurologyButton_.setText("Neurology");
      neurologyButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            neurologyButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 7;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(neurologyButton_, gridBagConstraints);

      ophtalmologyButton_.setText("Ophthalmology");
      ophtalmologyButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            ophtalmologyButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 8;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(ophtalmologyButton_, gridBagConstraints);

      orthopaedicsButton_.setText("Orthopedics");
      orthopaedicsButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            orthopaedicsButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 9;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(orthopaedicsButton_, gridBagConstraints);

      urologyButton_.setText("Urology");
      urologyButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            urologyButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 10;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(urologyButton_, gridBagConstraints);

      surgeryButton_.setText("Surgery");
      surgeryButton_.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            surgeryButton_ActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 11;
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
      backgroundDLP_.add(surgeryButton_, gridBagConstraints);

      guideLabel_.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
      guideLabel_.setForeground(new java.awt.Color(153, 153, 153));
      guideLabel_.setText("Press a Discipline from below to view Availabilities");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
      backgroundDLP_.add(guideLabel_, gridBagConstraints);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(backgroundDLP_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(0, 0, 0))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(backgroundDLP_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(0, 0, 0))
      );
   }// </editor-fold>//GEN-END:initComponents

   private void cardiologyButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardiologyButton_ActionPerformed
      
      try
         {
         
         doctors_ = DoctorManager.getDiscipline(cardiologyButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
      
   }//GEN-LAST:event_cardiologyButton_ActionPerformed

   private void pulmonologyButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulmonologyButton_ActionPerformed
      
      try
         {
            
         doctors_ = DoctorManager.getDiscipline(pulmonologyButton_.getText());
         showAvailabilities();
                  
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
      
   }//GEN-LAST:event_pulmonologyButton_ActionPerformed

   private void infectiousButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infectiousButton_ActionPerformed
      
      try
         {
            
         doctors_ = DoctorManager.getDiscipline(infectiousButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
      
   }//GEN-LAST:event_infectiousButton_ActionPerformed

   private void haematologyButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haematologyButton_ActionPerformed
      
       try
         {
            
         doctors_ = DoctorManager.getDiscipline(haematologyButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }     
      
   }//GEN-LAST:event_haematologyButton_ActionPerformed

   private void intensiveCareButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensiveCareButton_ActionPerformed
      
     try
         {
            
         doctors_ = DoctorManager.getDiscipline(intensiveCareButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
     
   }//GEN-LAST:event_intensiveCareButton_ActionPerformed

   private void neurologyButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neurologyButton_ActionPerformed
      
      try
         {
            
         doctors_ = DoctorManager.getDiscipline(neurologyButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
      
   }//GEN-LAST:event_neurologyButton_ActionPerformed

   private void ophtalmologyButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ophtalmologyButton_ActionPerformed
      
      try
         {
            
         doctors_ = DoctorManager.getDiscipline(ophtalmologyButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
      
   }//GEN-LAST:event_ophtalmologyButton_ActionPerformed

   private void orthopaedicsButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orthopaedicsButton_ActionPerformed
      
      try
         {
            
         doctors_ = DoctorManager.getDiscipline(orthopaedicsButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
      
   }//GEN-LAST:event_orthopaedicsButton_ActionPerformed

   private void urologyButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urologyButton_ActionPerformed
      
      try
         {
            
         doctors_ = DoctorManager.getDiscipline(urologyButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
      
   }//GEN-LAST:event_urologyButton_ActionPerformed

   private void surgeryButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeryButton_ActionPerformed
      
      try
         {
            
         doctors_ = DoctorManager.getDiscipline(surgeryButton_.getText());
         showAvailabilities();
         
         }
      catch (NullPointerException e)
         {
         
         System.out.println(e); 
         
         }
      
   }//GEN-LAST:event_surgeryButton_ActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel backgroundDLP_;
   private javax.swing.JButton cardiologyButton_;
   private javax.swing.JLabel disciplinesTitleLabel_;
   private javax.swing.JLabel guideLabel_;
   private javax.swing.JButton haematologyButton_;
   private javax.swing.JButton infectiousButton_;
   private javax.swing.JButton intensiveCareButton_;
   private javax.swing.JButton neurologyButton_;
   private javax.swing.JButton ophtalmologyButton_;
   private javax.swing.JButton orthopaedicsButton_;
   private javax.swing.JButton pulmonologyButton_;
   private javax.swing.JButton surgeryButton_;
   private javax.swing.JButton urologyButton_;
   // End of variables declaration//GEN-END:variables
}
