/*

Part of the ViewAvailableDoctorPanel, which uses GridLayout to set 3 columns
This panel is added in the right column to show details of the selected Available Doctor

By Daniel Vella

*/

package gui;

import defaultpackage.Doctor;
import defaultpackage.Surgeon;
import java.awt.Color;
import java.util.Objects;

public class RightDoctorsDetailsPanel extends javax.swing.JPanel 
   {
   
   private String name_;
   private String contact_;
   private String contactId_;
   private boolean certificate_;

   public RightDoctorsDetailsPanel() 
      {
         
      initComponents();
      
      }
   
   public void setDoctorDetails(Doctor doctor)
      {
         
      this.name_ = doctor.getName();
      this.contact_ = doctor.getContactMethod();
      this.contactId_ = doctor.getContactDetails();
      
      nameOutputLabel_.setText(name_);
      contactOutputLabel_.setText(contact_);
      contactIdOutputLabel_.setText(contactId_);
      
      // If Doctor is a surgeon, flag for certificate validity
      if (Objects.equals(doctor.getDiscipline(), "Surgery"))
         {
            
         this.certificate_ = ((Surgeon)doctor).getCertificate().isExpired();
         certificateIcon_.setVisible(true);
         certificateLabel_.setVisible(true);
         certificateOutputLabel_.setVisible(true); 
           
         if (!certificate_)
            {
            
            certificateOutputLabel_.setText("VALID CERTIFICATE");
            certificateOutputLabel_.setForeground(Color.GREEN);
               
            }
         else  
            {
            
            certificateOutputLabel_.setText("INVALID CERTIFICATE");
            certificateOutputLabel_.setForeground(Color.RED);        
                    
            }
     
         } 
      
      // if not surgeon, hide certificate fields
      else 
         {
         
         certificateIcon_.setVisible(false);
         certificateLabel_.setVisible(false);
         certificateOutputLabel_.setVisible(false);   
            
         }  
      
      }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      backgroundDDP_ = new javax.swing.JPanel();
      doctorDetailsTitleLabel_ = new javax.swing.JLabel();
      nameLabel_ = new javax.swing.JLabel();
      contactLabel_ = new javax.swing.JLabel();
      contactIdLabel_ = new javax.swing.JLabel();
      certificateLabel_ = new javax.swing.JLabel();
      nameOutputLabel_ = new javax.swing.JLabel();
      contactOutputLabel_ = new javax.swing.JLabel();
      contactIdOutputLabel_ = new javax.swing.JLabel();
      certificateOutputLabel_ = new javax.swing.JLabel();
      nameIcon_ = new javax.swing.JLabel();
      contactIcon_ = new javax.swing.JLabel();
      contactIdIcon_ = new javax.swing.JLabel();
      certificateIcon_ = new javax.swing.JLabel();

      setBackground(new java.awt.Color(255, 255, 255));

      backgroundDDP_.setBackground(new java.awt.Color(255, 255, 255));
      backgroundDDP_.setMaximumSize(new java.awt.Dimension(1000, 1000));
      backgroundDDP_.setLayout(new java.awt.GridBagLayout());

      doctorDetailsTitleLabel_.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
      doctorDetailsTitleLabel_.setText("Doctor Details");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.gridwidth = 3;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.insets = new java.awt.Insets(0, 30, 150, 0);
      backgroundDDP_.add(doctorDetailsTitleLabel_, gridBagConstraints);

      nameLabel_.setForeground(new java.awt.Color(51, 51, 51));
      nameLabel_.setText("Name");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
      backgroundDDP_.add(nameLabel_, gridBagConstraints);

      contactLabel_.setForeground(new java.awt.Color(51, 51, 51));
      contactLabel_.setText("Contact");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
      backgroundDDP_.add(contactLabel_, gridBagConstraints);

      contactIdLabel_.setForeground(new java.awt.Color(51, 51, 51));
      contactIdLabel_.setText("Contact ID");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
      backgroundDDP_.add(contactIdLabel_, gridBagConstraints);

      certificateLabel_.setForeground(new java.awt.Color(51, 51, 51));
      certificateLabel_.setText("Certification");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 4;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
      backgroundDDP_.add(certificateLabel_, gridBagConstraints);

      nameOutputLabel_.setBackground(new java.awt.Color(255, 255, 255));
      nameOutputLabel_.setForeground(new java.awt.Color(153, 153, 153));
      nameOutputLabel_.setText("Populate from System");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 50);
      backgroundDDP_.add(nameOutputLabel_, gridBagConstraints);

      contactOutputLabel_.setForeground(new java.awt.Color(153, 153, 153));
      contactOutputLabel_.setText("Populate from System");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 50);
      backgroundDDP_.add(contactOutputLabel_, gridBagConstraints);

      contactIdOutputLabel_.setForeground(new java.awt.Color(153, 153, 153));
      contactIdOutputLabel_.setText("Populate from System");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 50);
      backgroundDDP_.add(contactIdOutputLabel_, gridBagConstraints);

      certificateOutputLabel_.setForeground(new java.awt.Color(153, 153, 153));
      certificateOutputLabel_.setText("Populate from System");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 2;
      gridBagConstraints.gridy = 4;
      gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 50);
      backgroundDDP_.add(certificateOutputLabel_, gridBagConstraints);

      nameIcon_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nameIcon.png"))); // NOI18N
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 20);
      backgroundDDP_.add(nameIcon_, gridBagConstraints);

      contactIcon_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/preferredIcon.png"))); // NOI18N
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 2;
      gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 20);
      backgroundDDP_.add(contactIcon_, gridBagConstraints);

      contactIdIcon_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactIcon.png"))); // NOI18N
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 3;
      gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 20);
      backgroundDDP_.add(contactIdIcon_, gridBagConstraints);

      certificateIcon_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/certificateIcon.png"))); // NOI18N
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 4;
      gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 20);
      backgroundDDP_.add(certificateIcon_, gridBagConstraints);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(backgroundDDP_, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(backgroundDDP_, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel backgroundDDP_;
   private javax.swing.JLabel certificateIcon_;
   private javax.swing.JLabel certificateLabel_;
   private javax.swing.JLabel certificateOutputLabel_;
   private javax.swing.JLabel contactIcon_;
   private javax.swing.JLabel contactIdIcon_;
   private javax.swing.JLabel contactIdLabel_;
   private javax.swing.JLabel contactIdOutputLabel_;
   private javax.swing.JLabel contactLabel_;
   private javax.swing.JLabel contactOutputLabel_;
   private javax.swing.JLabel doctorDetailsTitleLabel_;
   private javax.swing.JLabel nameIcon_;
   private javax.swing.JLabel nameLabel_;
   private javax.swing.JLabel nameOutputLabel_;
   // End of variables declaration//GEN-END:variables
}
